### ISSUE TITLE
Is it possible to port this to 1.12.2?

### ISSUE THREAD

**Issue by ja2ui0** [adde0109/Proxy-Compatible-Forge#14]
Velocity only supports Forge <1.13 using legacy forwarding.

I'm running a Velocity network with a mix of Paper and Fabric hosts with modern forwarding, and I'd like to put a Forge 1.12.2 server in that lobby without failing back to legacy Bukkit (which isn't supported by modern fabric anyway).

**Comment by adde0109** [comment]
No, I'm sorry. This isn't practical because of the old handshake protocol that 1.12.2 use. It's not impossible but it would require significant work to port modern forwarding to this version.

**Comment by blryface** [comment]
that aged well
