### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by UnperishedDev** [adde0109/Proxy-Compatible-Forge#21]
## Tried joining my 1.19.2 forge server (for the first time)  but got this error:

[10May2023 18:34:49.364] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world

  | java.lang.NullPointerException: Cannot invoke "net.minecraftforge.network.ConnectionData.getChannels()" because "connectionData" is null
  | at net.minecraft.commands.Commands.redirect$zzb000$sendCommands$grabPacket(Commands.java:523) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.commands.Commands.m_82095_(Commands.java:298) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.players.PlayerList.m_11226_(PlayerList.java:590) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.players.PlayerList.m_11289_(PlayerList.java:483) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:176) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?]
  |  

## Stated reason after the error message:

[Player] kicked from server ForgeTestServer: multiplayer.disconnect.invalid_player_data

## Other, possibly helpful information:

Do you happen to know what may be causing this? I have one mod installed client-side (fork of Forge Client Reset Packet for 1.19.2). I have Ambassador installed on the proxy and I seem to have configured everything properly. I have not done anything in the Minecraft world that might cause a player data issue, I haven't even gotten to join the world properly yet. This mod is the only mod installed on the server.

**Note that the setup does work on 1.16.5, just not 1.19.2. I have not tested 1.18.2**.

**Comment by UnperishedDev** [comment]
Note that the setup does work on 1.16.5

**Comment by adde0109** [comment]
Could you provide the debug.log log from the server during the join?

**Comment by UnperishedDev** [comment]
> Could you provide the debug.log log from the server during the join?

I don’t have access to that with my hosting provider, but I can give you [the entire log](https://mclo.gs/Gy6mG1D).

**Comment by UnperishedDev** [comment]
Really odd coincidence, I logged on today and it works just fine. My apologies. (I had previously started/restarted the server, no idea why it's working now but wasn't before. Perhaps my client's issue?)
