### ISSUE TITLE
This mod does not work in Minecraft version 1.18.2

### ISSUE THREAD

**Issue by Joe-REAL-0** [adde0109/Proxy-Compatible-Forge#28]
Velocity version : 3.2.0
mod version : 1.18.2 - v1.4.4
I followed the instructions in README to configure config, set the velocity secret in the subserver,but when I try to connect the subserver,It still return this:

**Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact yo
ur server admin for more details.**

and the console logged a error :

**Channels [upgradednetherite_items:main,utilitix:netchannel,yes_steve_model:network,inventorysorter:net,mantle:network,bong
o:netchannel,jea:netchannel,upgradednetherite:main,libx:netchannel,curios:main,tconstruct:network,botania:main,bloodmagic:main,quark:main,bi
ngolobby:netchannel,immersiveengineering:main,minemention:netchannel,mekanism:mekanism,patchouli:main,lootr:main_network_channel,create:main
] rejected vanilla connections**

This situation has no different from when I didn't install the mod, and I'm sorry I can't provide any information related to bugs of the mod

**Comment by adde0109** [comment]
Did you connect using a proxy tha supports modern foege?

**Comment by Joe-REAL-0** [comment]
> Did you connect using a proxy tha supports modern forge?

Hadn't yet. Acturally I don’t know which proxy support mordern forge.

**Comment by adde0109** [comment]
https://github.com/adde0109/Ambassador
You could use this plugin with velocity in order for it to work.

**Comment by adde0109** [comment]
You need to set the proxy forwarding mode to modern if you want to use modern player info forwarding

**Comment by Joe-REAL-0** [comment]
> Looks like you didn't configure the player forwarding correctly. You need to set the proxy forwarding mode to modern if you want to use modern player info forwarding

The server group I'm running has some sub-servers with version 1.12.2, so I can't switch player forwarding to modern because it would make those sub-servers unable to connect. However, the plugin you provided almost solves my problem. Now I can connect my 1.13+ forge server through the proxy, even though players will encounter an error when connecting via console. Anyway, this error doesn't affect gameplay in any way.

**Comment by unilock** [comment]
You could try [BungeeForge](https://github.com/caunt/BungeeForge) (alongside Ambassador) to enable "legacy" player info forwarding for pre-1.13 Forge servers.
