### ISSUE TITLE
using with version 1.20.2 forge

### ISSUE THREAD

**Issue by elizabeth-suehr** [adde0109/Proxy-Compatible-Forge#29]
Hello people, 

I might have done something wrong, but I believe this is not working with 1.20.2 right now.  Forge was updated about 13 days ago, so maybe its not up to date. I tried changing the dependency but wasn't able to built it, haven't worked with java in forever...

Thanks!!

**Comment by p0t4t0sandwich** [comment]
Currently in the process of updating PCF, it's functional, and I just need to tidy things up a bit

**Comment by p0t4t0sandwich** [comment]
v1.1.5 now supports this
