### ISSUE TITLE
config file is not created on 1.20.1

### ISSUE THREAD

**Issue by czychuuu** [adde0109/Proxy-Compatible-Forge#30]
title, tried with 1.1.3 and 1.1.4 same results

**Comment by adde0109** [comment]
More info about your setup is needed. What server software?

**Comment by goteusz-maszyk** [comment]
Maybe noeforge fault? I use it and the mod is completely ignored by neo

**Comment by Y1rd** [comment]
The file should be `pcf-common.toml`, the mod description is outdated.

**Comment by p0t4t0sandwich** [comment]
Fixed the mod's description on Modrinth
