### ISSUE TITLE
(1.20.1) Channels [cfm:network] rejected vanilla connections

### ISSUE THREAD

**Issue by JustAiden9** [adde0109/Proxy-Compatible-Forge#32]
I am able to join my main hub server under Velocity. But when I do /server msmp I get this error in the logs below, I will also put the full log file in here + I have forge installed and the exact mods:
Channels [cfm:network] rejected vanilla connections
[latest.log](https://github.com/adde0109/Proxy-Compatible-Forge/files/15357240/latest.log)

**Comment by adde0109** [comment]
Please provide Velocity logs.

**Comment by JustAiden9** [comment]
I got it fixed I did not know I had to install Ambassador to my Velocity proxy.

**Comment by adde0109** [comment]
Closing it as it seems to be resolved.
