### ISSUE TITLE
crash when using this

### ISSUE THREAD

**Issue by Ax3dGaming** [adde0109/Proxy-Compatible-Forge#34]
I don't know if I should report this here, but I have a crash when trying to log in with this.
logs: https://mclo.gs/GvPS20W

**Comment by Sander0542** [comment]
Related to https://github.com/PaperMC/Velocity/issues/1370

**Comment by ajh123** [comment]
That's an error with https://github.com/adde0109/Ambassador not Proxy-Compatible-Forge. You cannot instll Proxy-Compatible-Forge on Velocity.

**Comment by p0t4t0sandwich** [comment]
Looks similar to the weird Amassador + 1.20.5 packet arg issue, which is fixed in a pending PR.
If it's still an issue, feel free to create an issue over in the Ambassador repo with Client, Velocity, and Forge logs.
